version: '3'
volumes:
  vol0:
  vol1:
  vol2:
  vol3:
services:
  nd0:
    image: sorock:dev
    environment:
      URI: http://nd0:50000
      CAP: 1TiB
    ports:
      - 50000:50000
    volumes:
      - vol0:/var/lib/sorock/data

  nd1:
    image: sorock:dev
    environment:
      URI: http://nd1:50000
      CAP: 2.5TiB
    ports:
      - 50001:50000
    volumes:
      - vol1:/var/lib/sorock/data

  nd2:
    image: sorock:dev
    environment:
      URI: http://nd2:50000
      CAP: 10TiB
    ports:
      - 50002:50000
    volumes:
      - vol2:/var/lib/sorock/data

  nd3:
    image: sorock:dev
    environment:
      URI: http://nd3:50000
      CAP: 300GiB
    ports:
      - 50003:50000
    volumes:
      - vol3:/var/lib/sorock/data